### PR TITLE
Architectural improvements were made. Logic has left the ui. Added do…

### PR DESCRIPTION
**Pull request by merttoptas**
Hi,
I reviewed your project and wanted to make some changes. With the changes, you can expand the project more comfortably. I tried to implement the architectural structure suggested by Google.

### CODE REVIEW

**Comment by nisaefendioglu** [comment]
> Hi, I reviewed your project and wanted to make some changes. With the changes, you can expand the project more comfortably. I tried to implement the architectural structure suggested by Google.

It was an application that I developed quickly. Thank you so much, this is so much better. 🥳

**Comment by nisaefendioglu** [comment]
When I click the Generate Password button, I can't get interaction without making a selection (uppercase or lowercase). Can you check it?

**Comment by merttoptas** [comment]
Let me test and check the bug

**Comment by nisaefendioglu** [comment]
> Let me test and check the bug

Thank you so much. Controls depended on the state of the switch structure being open. Password was not generated when uppercase or lowecase was not selected. For this, I tried to use the control you wrote by turning it into a method and giving it the necessary values. Seems to be ok now

**Pull request merged**
